version: '3'
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:Z
    environment:
      - ENVIRONMENT=development
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:Z
      - /app/node_modules
    environment:
      - ENVIRONMENT=development
    depends_on:
      - backend